#!/usr/bin/env python3
"""
Auto-generated Policy Enforcement Engine
Generated by SPL Compiler
"""

from datetime import datetime
from typing import Dict, List, Any


class PolicyEngine:
    """Policy enforcement engine for SPL policies."""
    
    def __init__(self):
        self.roles = {'admin': ['read', 'write', 'execute', 'delete'], 'Developer': ['read', 'write'], 'Guest': ['read']}
        self.resources = ['DB_Finance', 'DB_Public', 'API_Internal']
        self.policies = []
        self._load_policies()
    
    def _load_policies(self):
        """Load all policies into memory."""
        self.policies.append({'type': 'ALLOW', 'actions': ['read', 'write'], 'resource': 'DB_Finance'})
        self.policies.append({'type': 'DENY', 'actions': ['delete'], 'resource': 'DB_Finance'})
        self.policies.append({'type': 'ALLOW', 'actions': ['read'], 'resource': 'DB_Public'})
        self.policies.append({'type': 'DENY', 'actions': ['*'], 'resource': 'API_Internal'})
    
    def check_access(self, user: str, action: str, resource: str, 
                    context: Dict[str, Any] = None) -> bool:
        """
        Check if user has permission to perform action on resource.
        
        Args:
            user: Username or user identifier
            action: Action to perform (read, write, delete, etc.)
            resource: Resource identifier
            context: Additional context (time, IP, etc.)
        
        Returns:
            bool: True if access is allowed, False otherwise
        """
        context = context or {}
        
        # Check all policies
        deny_found = False
        allow_found = False
        
        for policy in self.policies:
            # Check if action matches
            if action not in policy['actions']:
                continue
            
            # Check if resource matches
            if not self._resource_matches(resource, policy['resource']):
                continue
            
            # Policy matches - check type
            if policy['type'] == 'DENY':
                deny_found = True
            elif policy['type'] == 'ALLOW':
                allow_found = True
        
        # Deny overrides allow
        if deny_found:
            return False
        
        return allow_found
    
    def _resource_matches(self, resource: str, pattern: str) -> bool:
        """Check if resource matches pattern (supports wildcards)."""
        if pattern == '*':
            return True
        if '*' in pattern:
            import re
            regex = pattern.replace('*', '.*')
            return bool(re.match(regex, resource))
        return resource == pattern


def main():
    """Test the policy engine."""
    engine = PolicyEngine()
    
    # Example access checks
    test_cases = [
        ('admin', 'read', 'DB_Finance'),
        ('guest', 'delete', 'DB_Finance'),
        ('developer', 'write', 'DB_Finance'),
    ]
    
    print('Policy Engine Test Results:')
    print('-' * 50)
    for user, action, resource in test_cases:
        allowed = engine.check_access(user, action, resource)
        status = ' ALLOWED' if allowed else ' DENIED'
        print(f'{status}: {user} -> {action} on {resource}')


if __name__ == '__main__':
    main()