from parsing.RPLParserVisitor import RPLParserVisitor


class CodeGenerator(RPLParserVisitor):
    """
    Generates executable Python code from SPL policies.
    Creates a policy enforcement engine.
    """

    def __init__(self):
        self.code_lines = []
        self.indent_level = 0
        self.roles = {}
        self.resources = {}
        self.policies = []

    def emit(self, code):
        """Emit a line of code with proper indentation."""
        indent = "    " * self.indent_level
        self.code_lines.append(indent + code)

    def generate(self, tree):
        """Generate complete Python program from parse tree."""
        # Generate header
        self.emit("#!/usr/bin/env python3")
        self.emit('"""')
        self.emit("Auto-generated Policy Enforcement Engine")
        self.emit("Generated by SPL Compiler")
        self.emit('"""')
        self.emit("")
        self.emit("from typing import Dict, List, Any")
        self.emit("")

        # Visit tree to collect data
        self.visit(tree)

        # Generate policy enforcement class
        self.generate_policy_engine()

        # Generate main function
        self.generate_main()

        return "\n".join(self.code_lines)

    def visitRoleDeclaration(self, ctx):
        """Collect role information."""
        role_name = ctx.IDENTIFIER().getText()
        permissions = []
        for perm_ctx in ctx.rolePermissions().permission():
            permissions.append(perm_ctx.getText())
        self.roles[role_name] = permissions
        return None

    def visitResourceDeclaration(self, ctx):
        """Collect resource information."""
        resource_name = ctx.IDENTIFIER().getText()
        self.resources[resource_name] = resource_name
        return None

    def visitPolicyRule(self, ctx):
        """Collect policy rules."""
        policy = {
            'type': ctx.policyType().getText(),
            'actions': [a.getText() for a in ctx.actionList().permission()],
            'resource': ctx.resourceRef().getText().strip('"\''),
            'has_condition': ctx.ifClause() is not None
        }
        self.policies.append(policy)
        return None

    def generate_policy_engine(self):
        """Generate PolicyEngine class."""
        self.emit("")
        self.emit("class PolicyEngine:")
        self.indent_level += 1

        self.emit('"""Policy enforcement engine for SPL policies."""')
        self.emit("")

        # Constructor
        self.emit("def __init__(self):")
        self.indent_level += 1
        self.emit("self.roles = " + repr(self.roles))
        self.emit("self.resources = " + repr(list(self.resources.keys())))
        self.emit("self.policies = []")
        self.emit("self._load_policies()")
        self.indent_level -= 1
        self.emit("")

        # Load policies method
        self.emit("def _load_policies(self):")
        self.indent_level += 1
        self.emit('"""Load all policies into memory."""')

        for policy in self.policies:
            policy_dict = (
                f"{{'type': '{policy['type']}', "
                f"'actions': {policy['actions']}, "
                f"'resource': '{policy['resource']}'}}"
            )
            self.emit(f"self.policies.append({policy_dict})")

        self.indent_level -= 1
        self.emit("")

        # Check access method
        self.emit("def check_access(self, user: str, action: str, resource: str, ")
        self.emit("                context: Dict[str, Any] = None) -> bool:")
        self.indent_level += 1
        self.emit('"""')
        self.emit("Check if user has permission to perform action on resource.")
        self.emit("")
        self.emit("Args:")
        self.emit("    user: Username or user identifier")
        self.emit("    action: Action to perform (read, write, delete, etc.)")
        self.emit("    resource: Resource identifier")
        self.emit("    context: Additional context (time, IP, etc.)")
        self.emit("")
        self.emit("Returns:")
        self.emit("    bool: True if access is allowed, False otherwise")
        self.emit('"""')
        self.emit("context = context or {}")
        self.emit("")
        self.emit("# Check all policies")
        self.emit("deny_found = False")
        self.emit("allow_found = False")
        self.emit("")
        self.emit("for policy in self.policies:")
        self.indent_level += 1
        self.emit("# Check if action matches")
        self.emit("if action not in policy['actions']:")
        self.indent_level += 1
        self.emit("continue")
        self.indent_level -= 1
        self.emit("")
        self.emit("# Check if resource matches")
        self.emit("if not self._resource_matches(resource, policy['resource']):")
        self.indent_level += 1
        self.emit("continue")
        self.indent_level -= 1
        self.emit("")
        self.emit("# Policy matches - check type")
        self.emit("if policy['type'] == 'DENY':")
        self.indent_level += 1
        self.emit("deny_found = True")
        self.indent_level -= 1
        self.emit("elif policy['type'] == 'ALLOW':")
        self.indent_level += 1
        self.emit("allow_found = True")
        self.indent_level -= 1
        self.indent_level -= 1
        self.emit("")
        self.emit("# Deny overrides allow")
        self.emit("if deny_found:")
        self.indent_level += 1
        self.emit("return False")
        self.indent_level -= 1
        self.emit("")
        self.emit("return allow_found")
        self.indent_level -= 1
        self.emit("")

        # Resource matching helper
        self.emit("def _resource_matches(self, resource: str, pattern: str) -> bool:")
        self.indent_level += 1
        self.emit('"""Check if resource matches pattern (supports wildcards)."""')
        self.emit("if pattern == '*':")
        self.indent_level += 1
        self.emit("return True")
        self.indent_level -= 1
        self.emit("if '*' in pattern:")
        self.indent_level += 1
        self.emit("import re")
        self.emit("regex = pattern.replace('*', '.*')")
        self.emit("return bool(re.match(regex, resource))")
        self.indent_level -= 1
        self.emit("return resource == pattern")
        self.indent_level -= 1

        self.indent_level -= 1
        self.emit("")

    def generate_main(self):
        """Generate main function for testing."""
        self.emit("")
        self.emit("def main():")
        self.indent_level += 1
        self.emit('"""Test the policy engine."""')
        self.emit("engine = PolicyEngine()")
        self.emit("")
        self.emit("# Example access checks")
        self.emit("test_cases = [")
        self.indent_level += 1
        self.emit("('admin', 'read', 'DB_Finance'),")
        self.emit("('guest', 'delete', 'DB_Finance'),")
        self.emit("('developer', 'write', 'DB_Finance'),")
        self.indent_level -= 1
        self.emit("]")
        self.emit("")
        self.emit("print('Policy Engine Test Results:')")
        self.emit("print('-' * 50)")
        self.emit("for user, action, resource in test_cases:")
        self.indent_level += 1
        self.emit("allowed = engine.check_access(user, action, resource)")
        self.emit("status = '^ ALLOWED' if allowed else '* DENIED'")
        self.emit("print(f'{status}: {user} -> {action} on {resource}')")
        self.indent_level -= 1
        self.indent_level -= 1
        self.emit("")

        self.emit("")
        self.emit("if __name__ == '__main__':")
        self.indent_level += 1
        self.emit("main()")
        self.indent_level -= 1
